traefik:
    ports:
        - ${admin_port}:${admin_port}/tcp
        - ${http_port}:${http_port}/tcp
        - ${https_port}:${https_port}/tcp
    labels:
        io.rancher.scheduler.global: 'true'
        io.rancher.sidekicks: traefik-conf
        io.rancher.container.pull_image: always
        io.rancher.container.hostname_override: container_name
        io.rancher.scheduler.affinity:host_label: traefik_lb=true
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    tty: true
    log_driver: ''
    log_opt: {}
    image: traefik:v1.0.0-rc2
    environment:
        - TRAEFIK_HTTP_PORT=${http_port}
        - TRAEFIK_ADMIN_PORT=${admin_port}
        - CONF_INTERVAL=${refresh_interval}
    volumes_from:
        - traefik-conf
traefik-conf:
    labels:
        io.rancher.scheduler.global: 'true'
        io.rancher.container.start_once: 'true'
        io.rancher.scheduler.affinity:host_label: traefik_lb=true
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
        io.rancher.container.pull_image: always
    tty: true
    log_driver: ''
    log_opt: {}
    image: connorpoole/traefik-conf:latest

