.catalog:
  name: Traefik
  version: v1.0.0-rc2
  description: |
    (Experimental) Traefik active load balancer.
  minimum_rancher_version: v1.0.0
  maintainer: "Raul Sanchez <rawmind@gmail.com>"
  uuid: traefik-0
  questions:
    - variable: "http_port"
      description: "Traefik http public port to listen."
      label: "Http port:"
      required: true
      default: 80
      type: "int"
    - variable: "https_port"
      description: "Traefik https public port to listen."
      label: "Https port:"
      required: true
      default: 443
      type: "int"
    - variable: "admin_port"
      description: "Traefik admin public port to listen."
      label: "Admin port:"
      required: true
      default: 8080
      type: "string"
    - variable: "refresh_interval"
      description: "Interval to poll/apply configuration changes." 
      label: "Refresh Interval (s):"
      required: true
      default: 60 
      type: "int"
    - variable: "tomlConfig"
      description: "TOML config for traeffik https://docs.traefik.io/toml/"
      label: "toml config"
      required: true
      type: "multiline"
      default: |
        ###############################################################
        #traefik toml configuration
        ################################################################
        [entryPoints]
          [entryPoints.http]
            address = ":80"
          [entryPoints.https]
            address = ":443"
        # Enable the api backend
        [web]
          address = ":8080"
        # Enable Consul Catalog configuration backend
        [backends]
          [consulCatalog]
            endpoint = "127.0.0.1:8500"
            domain = "consul.localhost"
            prefix = "traefik"
traefik:
  retain_ip: true
  health_check:
    port: ${admin_port}
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET /dashboard/# HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 5000
  metadata:
    config:
      tomlConfig: |
        ${tomlConfig}
